# -*- coding: utf-8 -*-
"""Sentinelnet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrwV0tMwlNdFMkM2SD1kcS-Fu9HRIbr2
"""

import pandas as pd

df = pd.read_csv("KDDTrain+.txt", header=None)
df.shape, df.head()

# Official 41 NSL-KDD feature names
feature_names = [
"duration","protocol_type","service","flag","src_bytes","dst_bytes",
"land","wrong_fragment","urgent","hot","num_failed_logins","logged_in",
"num_compromised","root_shell","su_attempted","num_root","num_file_creations",
"num_shells","num_access_files","num_outbound_cmds","is_host_login",
"is_guest_login","count","srv_count","serror_rate","srv_serror_rate",
"rerror_rate","srv_rerror_rate","same_srv_rate","diff_srv_rate",
"srv_diff_host_rate","dst_host_count","dst_host_srv_count",
"dst_host_same_srv_rate","dst_host_diff_srv_rate",
"dst_host_same_src_port_rate","dst_host_srv_diff_host_rate",
"dst_host_serror_rate","dst_host_srv_serror_rate",
"dst_host_rerror_rate","dst_host_srv_rerror_rate"
]

# Add the last 2 columns
feature_names += ["attack_type", "difficulty_level"]

# Assign names to dataframe
df.columns = feature_names

df.head()

# Mentor-provided attack category lists
dos_attacks = ['back', 'land', 'neptune', 'pod', 'smurf', 'teardrop',
               'apache2', 'mailbomb', 'processtable', 'udpstorm', 'worm',
               'buffer_overflow']

probe_attacks = ['satan', 'ipsweep', 'nmap', 'portsweep', 'mscan', 'saint']

r2l_attacks = ['guess_passwd', 'ftp_write', 'imap', 'phf', 'multihop',
               'warezmaster', 'warezclient', 'spy', 'xlock', 'xsnoop',
               'snmpgetattack', 'snmpguess', 'httptunnel', 'sendmail',
               'named']

u2r_attacks = ['rootkit', 'perl', 'loadmodule', 'ps', 'sqlattack']


# Function to map raw attack to category
def map_attack(label):
    label = label.strip().lower()
    if label in dos_attacks:
        return "DoS"
    elif label in probe_attacks:
        return "Probe"
    elif label in r2l_attacks:
        return "R2L"
    elif label in u2r_attacks:
        return "U2R"
    else:
        return "normal"

# Apply the mapping
df['attack_category'] = df['attack_type'].apply(map_attack)

# Display first few rows to verify
df[['attack_type', 'attack_category']].head(10)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df['protocol_type'].unique()
df['service'].unique()
df['flag'].unique()

df = df.dropna()
df.shape

df = df.drop(columns=['num_outbound_cmds'])
df.shape

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df['protocol_type'] = encoder.fit_transform(df['protocol_type'])
df['service'] = encoder.fit_transform(df['service'])
df['flag'] = encoder.fit_transform(df['flag'])

df[['protocol_type', 'service', 'flag']].head()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# All columns except the labels
numeric_cols = df.drop(columns=['attack_type', 'attack_category']).columns

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

from sklearn.model_selection import train_test_split

# Features (everything except attack labels)
X = df.drop(columns=['attack_type', 'attack_category'])

# Target (what we want to predict)
y = df['attack_category']

# 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

"""# Week 3: Feature Engineering and Selection

## Objective
The goal of this week is to identify the most important features for intrusion detection
and reduce redundancy using statistical and model-based techniques.

This notebook focuses on:
- Correlation analysis
- Feature importance analysis

"""

import seaborn as sns
import matplotlib.pyplot as plt

# take only numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# correlation matrix
corr = numeric_df.corr()

# plot heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(corr, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

!ls

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plt

# Encode target labels
le = LabelEncoder()
y = le.fit_transform(df['attack_category'])

# Features (drop labels)
X = df.drop(columns=['attack_type', 'attack_category'])

# Train Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X, y)

# Feature importance
importances = rf.feature_importances_
feature_importance = pd.Series(importances, index=X.columns).sort_values(ascending=False)

# Plot top 15 features
feature_importance.head(15).plot(kind='bar', figsize=(10,5))
plt.title("Top 15 Feature Importances")
plt.ylabel("Importance")
plt.show()

# Find highly correlated feature pairs (> 0.8)
high_corr = corr.abs().unstack().sort_values(ascending=False)
high_corr = high_corr[high_corr < 1]  # remove self-correlation
high_corr.head(10)

# Display top 10 important features
feature_importance.head(10)

# Select top 15 features based on importance
top_features = feature_importance.head(15).index.tolist()
top_features

"""# Week 4: Supervised Model Training

## Objective
The objective of this week is to train supervised machine learning models
to classify network traffic into different attack categories and evaluate
their performance using standard metrics.

In this phase:
- Supervised models such as Logistic Regression and Random Forest are trained
- Model performance is evaluated using Accuracy, Precision, Recall, and F1-score

"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Features (drop labels)
X = df.drop(columns=['attack_type', 'attack_category'])

# Target
y = df['attack_category']

# Encode target labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

X_train.shape, X_test.shape

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Train Logistic Regression
lr = LogisticRegression(max_iter=1000, n_jobs=-1)
lr.fit(X_train, y_train)

# Predict on test data
y_pred_lr = lr.predict(X_test)

# Evaluation metrics
lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_precision = precision_score(y_test, y_pred_lr, average='weighted')
lr_recall = recall_score(y_test, y_pred_lr, average='weighted')
lr_f1 = f1_score(y_test, y_pred_lr, average='weighted')

lr_accuracy, lr_precision, lr_recall, lr_f1

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Train Random Forest
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_train, y_train)

# Predict on test data
y_pred_rf = rf.predict(X_test)

# Evaluation metrics
rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_precision = precision_score(y_test, y_pred_rf, average='weighted')
rf_recall = recall_score(y_test, y_pred_rf, average='weighted')
rf_f1 = f1_score(y_test, y_pred_rf, average='weighted')

rf_accuracy, rf_precision, rf_recall, rf_f1

import pandas as pd

# Create comparison table
results = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [lr_accuracy, rf_accuracy],
    "Precision": [lr_precision, rf_precision],
    "Recall": [lr_recall, rf_recall],
    "F1-Score": [lr_f1, rf_f1]
})

results

# Select best model based on F1-score
if rf_f1 > lr_f1:
    best_model = "Random Forest"
else:
    best_model = "Logistic Regression"

best_model

"""## Model Selection

Based on the evaluation metrics, Random Forest achieved higher accuracy and
F1-score compared to Logistic Regression. Therefore, Random Forest is selected
as the final supervised model for intrusion detection.

# Week 5: Anomaly Detection using Unsupervised Learning

## Objective
The objective of this week is to detect anomalous network traffic patterns
without using labeled data. Unsupervised learning techniques are used to
identify deviations from normal network behavior.

In this phase:
- Clustering and anomaly detection algorithms are applied
- Normal and anomalous traffic patterns are analyzed
"""

# Features only (no labels)
X_unsupervised = df.drop(columns=['attack_type', 'attack_category'])

# Use only NORMAL traffic to train anomaly detectors
X_normal = X_unsupervised[df['attack_category'] == 'normal']

X_unsupervised.shape, X_normal.shape

from sklearn.cluster import KMeans
import numpy as np

# Train K-Means on normal traffic
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(X_normal)

# Compute distance of all points to nearest cluster center
distances = kmeans.transform(X_unsupervised)
min_distance = np.min(distances, axis=1)

# Set anomaly threshold (top 5% farthest points)
threshold = np.percentile(min_distance, 95)

# Label anomalies: 1 = anomaly, 0 = normal
kmeans_anomaly = (min_distance > threshold).astype(int)

kmeans_anomaly[:10]

from sklearn.ensemble import IsolationForest

# Train Isolation Forest on normal traffic
iso_forest = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)
iso_forest.fit(X_normal)

# Predict anomalies on full dataset
# Output: 1 = normal, -1 = anomaly
iso_pred = iso_forest.predict(X_unsupervised)

# Convert to binary labels: 1 = anomaly, 0 = normal
iso_anomaly = (iso_pred == -1).astype(int)

iso_anomaly[:10]

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(min_distance, bins=50, color='skyblue', edgecolor='black')
plt.axvline(threshold, color='red', linestyle='--', label='Anomaly Threshold')
plt.xlabel("Distance to nearest cluster center")
plt.ylabel("Number of samples")
plt.title("K-Means Distance Distribution for Anomaly Detection")
plt.legend()
plt.show()

import numpy as np

labels, counts = np.unique(iso_anomaly, return_counts=True)

plt.figure(figsize=(6,4))
plt.bar(['Normal', 'Anomaly'], counts, color=['green', 'red'])
plt.ylabel("Number of samples")
plt.title("Isolation Forest Anomaly Detection Results")
plt.show()

import pandas as pd

# Ground truth: 1 = attack, 0 = normal
true_anomaly = (df['attack_category'] != 'normal').astype(int)

comparison = pd.DataFrame({
    "Method": ["K-Means", "Isolation Forest"],
    "Anomalies Detected": [
        kmeans_anomaly.sum(),
        iso_anomaly.sum()
    ],
    "True Attacks Detected": [
        ((kmeans_anomaly == 1) & (true_anomaly == 1)).sum(),
        ((iso_anomaly == 1) & (true_anomaly == 1)).sum()
    ],
    "False Alarms (Normal flagged)": [
        ((kmeans_anomaly == 1) & (true_anomaly == 0)).sum(),
        ((iso_anomaly == 1) & (true_anomaly == 0)).sum()
    ]
})

comparison

# Select best anomaly detector based on detection vs false alarms
if (comparison.loc[comparison['Method'] == 'Isolation Forest', 'True Attacks Detected'].values[0] -
    comparison.loc[comparison['Method'] == 'Isolation Forest', 'False Alarms (Normal flagged)'].values[0]) > \
   (comparison.loc[comparison['Method'] == 'K-Means', 'True Attacks Detected'].values[0] -
    comparison.loc[comparison['Method'] == 'K-Means', 'False Alarms (Normal flagged)'].values[0]):

    best_anomaly_model = "Isolation Forest"
else:
    best_anomaly_model = "K-Means"

best_anomaly_model

"""## Anomaly Detector Selection

Based on the comparison of true attack detection and false alarm rates,
Isolation Forest was selected as the preferred anomaly detection model,
as it better captures deviations from normal network behavior.

# Week 6: Model Evaluation and Fine-Tuning

## Objective
The objective of this week is to evaluate and compare different machine learning
models developed in previous weeks and improve their performance through
hyperparameter tuning.

In this phase:
- Supervised and unsupervised models are compared
- Hyperparameters are tuned using cross-validation
- Performance is analyzed using confusion matrix and ROC curve
"""

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Confusion matrix for Random Forest
cm = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(7,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - Random Forest")
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
import numpy as np

# Binarize the labels for multiclass ROC
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

# Predict probabilities
y_score = rf.predict_proba(X_test)

# Compute ROC curve and ROC area (macro-average)
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(len(classes)):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot ROC curves
plt.figure(figsize=(8,6))
for i in range(len(classes)):
    plt.plot(fpr[i], tpr[i], lw=2, label=f'Class {i} (AUC = {roc_auc[i]:.2f})')

plt.plot([0,1], [0,1], 'k--', lw=2)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve - Random Forest (Multiclass)')
plt.legend(loc='lower right')
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

# Grid Search with cross-validation
grid_search = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=3,
    scoring='f1_weighted',
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

# Best parameters
grid_search.best_params_

# Final selected model after tuning
best_rf_model = grid_search.best_estimator_

best_rf_model

"""## Final Model Selection and Evaluation Summary

After evaluating multiple supervised and unsupervised models:

- Logistic Regression was used as a baseline supervised model
- Random Forest achieved higher accuracy and F1-score and was selected
- Hyperparameters were tuned using GridSearchCV with cross-validation
- Confusion Matrix and ROC curves confirmed strong classification performance
- For anomaly detection, Isolation Forest was selected due to better detection
  of anomalous traffic with fewer false alarms

Therefore, the final intrusion detection system is based on:
- Tuned Random Forest for supervised classification
- Isolation Forest for unsupervised anomaly detection

# Milestone 4

## Week 7: Alert Generation and Logging

The objective of this week is to simulate real-time intrusion detection
by generating alerts for detected attacks and logging the results in
a readable format.
"""

# Use the final tuned supervised model
final_model = best_rf_model

# Predict on test data (simulate real-time)
test_predictions = final_model.predict(X_test)

test_predictions[:10]

import pandas as pd

# Convert numeric predictions back to labels
predicted_labels = le.inverse_transform(test_predictions)

# Create alert dataframe
alerts_df = pd.DataFrame({
    "Actual_Label": le.inverse_transform(y_test),
    "Predicted_Label": predicted_labels
})

# Generate alert column
alerts_df["Alert"] = alerts_df["Predicted_Label"].apply(
    lambda x: "INTRUSION ALERT" if x != "normal" else "Normal"
)

alerts_df.head(10)

# Save alerts to CSV
alerts_df.to_csv("intrusion_alerts_log.csv", index=False)

# Confirm file saved
alerts_df.shape

import joblib

# Save the final tuned Random Forest model
joblib.dump(best_rf_model, "ids_rf_model.pkl")

import numpy as np

# Save test data
np.save("X_test.npy", X_test)
np.save("y_test.npy", y_test)

import joblib
import numpy as np
import pandas as pd

# Load saved model
rf_model = joblib.load("ids_rf_model.pkl")

# Load saved test data
X_test_rt = np.load("X_test.npy")
y_test_rt = np.load("y_test.npy")

print("Model and test data loaded")
print("Test data shape:", X_test_rt.shape)

from datetime import datetime

# Predict on incoming (test) traffic
y_pred_rt = rf_model.predict(X_test_rt)

alerts = []

for i, pred in enumerate(y_pred_rt):
    # pred != 0 assumes 0 = normal (LabelEncoder)
    if pred != 0:
        alerts.append({
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "sample_index": i,
            "predicted_attack_label": pred
        })

print("Total alerts generated:", len(alerts))

import pandas as pd
import matplotlib.pyplot as plt

# Convert alerts list to DataFrame
alerts_df = pd.DataFrame(alerts)

# Safety check
if alerts_df.empty:
    print("No intrusions detected.")
else:
    print("Intrusions detected:", len(alerts_df))

# Save alerts to CSV
alerts_df.to_csv("real_time_alerts.csv", index=False)

# Save alerts to readable log file
with open("real_time_alerts.log", "w") as f:
    for _, row in alerts_df.iterrows():
        f.write(
            f"{row['timestamp']} | "
            f"Sample {row['sample_index']} | "
            f"Predicted Label {row['predicted_attack_label']}\n"
        )

alerts_df.head()

# Attack distribution
attack_counts = alerts_df["predicted_attack_label"].value_counts()

plt.figure(figsize=(6,4))
attack_counts.plot(kind="bar", edgecolor="black")
plt.xlabel("Predicted Attack Label")
plt.ylabel("Count")
plt.title("Attack Type Distribution")
plt.tight_layout()
plt.show()

# Alert trend
plt.figure(figsize=(6,4))
plt.plot(range(len(alerts_df)), range(1, len(alerts_df)+1))
plt.xlabel("Sample Index")
plt.ylabel("Cumulative Alerts")
plt.title("Alert Trend Over Time")
plt.tight_layout()
plt.show()

rf_model.predict(X_test[:1000])

# Select only feature columns (drop labels if present)
feature_df = df.drop(
    columns=["attack_type", "attack_category", "difficulty_level"],
    errors="ignore"
)

# Save preprocessed CSV
feature_df.to_csv("preprocessed_traffic.csv", index=False)

print("preprocessed_traffic.csv created")

import joblib

model = joblib.load("ids_rf_model.pkl")

model.feature_names_in_

import pandas as pd
import joblib

# load model to get correct feature list
model = joblib.load("ids_rf_model.pkl")
expected_features = list(model.feature_names_in_)

# take your existing dataframe
fixed_df = df.copy()

# 1. DROP extra columns (like num_outbound_cmds)
fixed_df = fixed_df.drop(
    columns=[col for col in fixed_df.columns if col not in expected_features],
    errors="ignore"
)

# 2. ADD missing columns (like difficulty_level) with 0
for col in expected_features:
    if col not in fixed_df.columns:
        fixed_df[col] = 0

# 3. REORDER columns to match training
fixed_df = fixed_df[expected_features]

# save final CSV
fixed_df.to_csv("preprocessed_traffic.csv", index=False)

print("preprocessed_traffic.csv fixed and created")

# THIS is the final feature set the model understands
X_final = df.drop(columns=['attack_type', 'attack_category'])

# sanity check: should be only numbers
print(X_final.dtypes.value_counts())

# save CSV for application
X_final.to_csv("final_preprocessed_input.csv", index=False)

print("final_preprocessed_input.csv created")

# Drop columns that were not used during training
X_final = df.drop(
    columns=[
        'attack_type',
        'attack_category',
        'num_outbound_cmds'  # <-- THIS IS THE KEY FIX
    ],
    errors='ignore'
)

# Double-check: all numeric
print(X_final.dtypes.value_counts())

# Save the FINAL correct CSV
X_final.to_csv("final_preprocessed_input.csv", index=False)

print("final_preprocessed_input.csv created (correct schema)")

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import joblib
import pandas as pd

# ---- Define categorical and numerical columns ----
categorical_cols = ['protocol_type', 'service', 'flag']
target_cols = ['attack_type', 'attack_category']

X = df.drop(columns=target_cols + ['num_outbound_cmds'], errors='ignore')
y = df['attack_category']

# ---- Encode categoricals ----
for col in categorical_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])

# ---- Train model (same as before) ----
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf.fit(X, y)

# ---- Save pipeline (preprocessing + model together) ----
joblib.dump(
    {
        "model": rf,
        "columns": X.columns.tolist(),
        "categorical_cols": categorical_cols
    },
    "ids_pipeline.pkl"
)

print("ids_pipeline.pkl saved")